### ISSUE TITLE
Enabling gapless playback causes the final song in play queue to repeat

### ISSUE THREAD

**Issue by nocalla** [VinylMusicPlayer/VinylMusicPlayer#604]

**Comment by vaguerant** [comment]
I really like Vinyl, but this issue means it can't be my main music player on Android. For now, I'd recommend Vinyl fans try https://github.com/MaxFour/Music-Player

Like Vinyl, it is a fork of https://github.com/kabouzeid/Phonograph, so there's not much friction going back and forth between Vinyl and Music, at least until this issue is resolved.

**Comment by vaguerant** [comment]
Actually just saw that this was previously reported in #435 and fixed in #495. So the issue is already resolved, there just haven't been any releases since then, so the build being served on app stores/the Releases tab here still has the bug.

**Comment by nocalla** [comment]
Oh well spotted. So a new build needs to be pushed to the Play Store to fix it.

**Comment by soncaokim** [comment]
Should be fixed (as metionned in comment https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/604#issuecomment-1264242392).
