### ISSUE TITLE
Choose whitelist directories

### ISSUE THREAD

**Issue by trymeouteh** [VinylMusicPlayer/VinylMusicPlayer#618]
**Is your feature request related to a problem? Please describe.**
Whitelist directory is always /storage/emulated/0/Music/

**Describe the solution you'd like**
Would like the option to choose one directory or multiple directories for whitelist

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by soncaokim** [comment]
White list directory is always the start folder, as mentioned in the settings screen.

To change the start folder (hence the whitelist):
With the Folders view (instead of Library view, you can switch via the app main drawer), you can navigate between folders and pick one as "start directory" (three dots menu on the right of the chosen folder).

**Comment by ellisonch** [comment]
> To change the start folder (hence the whitelist): With the Folders view (instead of Library view, you can switch via the app main drawer), you can navigate between folders and pick one as "start directory" (three dots menu on the right of the chosen folder).

This doesn't work when the music is on an SD card.  See, #626.
