### ISSUE TITLE
New music not detected until reboot

### ISSUE THREAD

**Issue by Cwpute** [VinylMusicPlayer/VinylMusicPlayer#721]
**Describe the bug**
When i add music files to the internal storage of my phone, Vinyl doesn't detect them right away, even if i force a scan of the library.
I have to restart the phone entirely, and when Vinyl opens, the files are detected automatically.
Something strange: this also occurs on fresh installs of Vinyl.

**To reproduce**
1. Add new music files to the internal storage, in the folders covered by the whitelist
2. Can't see them in Vinyl
3. Reinstall the app
4. Vinyl still can't see the new files
5. Reboot the phone to solve the issue

**Expected behavior**
vinyl should probably seethese new files, or at least after a rescan of the folders.

**Device info**
 - Device: Nokia TA-1157
 - Android Version: 11
 - Vinyl Music Player Version: 1.5.0

**Additional context**
I've previously had the same problem with [Music Player](https://github.com/MaxFour/Music-Player).
Other apps seem to discover new files easily on this phone: i've hade no problems discovering videos and pictures with [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery) for example.

**Comment by soncaokim** [comment]
As of now, Vinyl is relying on the Android's MediaStore facility (a builtin OS facility) to list available tracks in storage - and this is the case for some other music player apps as well.

The MediaStore often picks up the new tracks with some delay (seconds to minutes), but if it is not recognising the new tracks (until reboot), the app is not aware of them.

Sorry, I'm closing this issue since the bug is beyond the app's reach.

**Comment by soncaokim** [comment]
Hmm, do you want to make a submission / pull request for that? :-)

**Comment by Cwpute** [comment]
Sorry, i am only suggesting… i unfortunately don't have enough knowledge in coding to do that !

**Comment by soncaokim** [comment]
No worries, and thanks for the discussion
