### ISSUE TITLE
Usability concern when using landscape orientation 

### ISSUE THREAD

**Issue by User2564** [VinylMusicPlayer/VinylMusicPlayer#736]
**Describe the bug**
I consider the title and screenshot (redacted) to be fully descriptive but more than happy to add further detail if need be.

**To reproduce**

0. Go to 'Songs' tab.
1. Enable screen orientation rotation.
2. Switch to landscape.
3. Tap on an entry.
4. Experience the inability to use the "Play? | "Play Next" | "Add to playing queue" options.

As a side benefit this can also be used to trigger: https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/727.

**Expected behavior**
The options listed in step 4 are rendered such that I can easily make use of them while in landscape orientation.

**Device info**
Same device as in https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/727.

For reference:

App version: 1.5.0
App version code: 180
Android build version: compiler01131555
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.003 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 2023
Device model: V2023
Device product name: 2023E
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
ROM: Funtouch OS 12 Global, build #:  PD2038BF_EX_A_38.9.32

**Additional context**
![screenshot](https://user-images.githubusercontent.com/96469712/231921477-358e0bb8-dc48-4d08-9b17-aaf75252f6bf.jpg)
Resolution: 1080x2400
Screen size: 6.44 inches, 100.1 cm2 (~83.9% screen-to-body ratio)
Source: https://www.gsmarena.com/vivo_y70-10531.php

**Comment by Osiris-Team** [comment]
@User2564 I was not able to reproduce this.

What I did:
1. Go to 'Songs' tab. 
1. Enable screen orientation rotation.
1. Switch to landscape.
1. Tap on an entry. **(This directly plays the song and does not open its options menu)**
1. Experience the inability to use the "Play? | "Play Next" | "Add to playing queue" options. **(I pressed on the 3 dots to open the options menu and all the options work fine)**

**Comment by gilex-dev** [comment]
I could reproduce this issue on 1.5.0 on a Galaxy S7 with stock ROM (Android 8.0.0) and a Fire HD 10 9th gen (Fire OS 7.3.1.4).
On [1.5.2](https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/tag/1.5.2) (and I guess on [1.5.1](https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/tag/1.5.1) too) this still happens when changing the `Default action an tapping a song...` from `Play` to `Always ask for actions` (The default was changed in https://github.com/VinylMusicPlayer/VinylMusicPlayer/commit/c360c5a117c6fcb3e055709e3b21c0efbd83e03c)
Funnily enough, the dialog of this setting has the same bug as originally described by @User2564.
![image](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/101349541/f1dc59d8-a84c-4e2e-bae5-952c8b959210)
