### ISSUE TITLE
Album list that looks like Artist view

### ISSUE THREAD

**Issue by Cwpute** [VinylMusicPlayer/VinylMusicPlayer#756]
**Is your feature request related to a problem? Please describe.**
I have quite a bunch of albums in my collection (folders in fact, recognized as albums), and i like to browse through them to find something id like to listen to. problem is, the name of the albums are not usually shown in full lenght to me (i chose to have 3 albums per line: having 1 album per line would show the whole title but be very inneficient for browsing) which is a bummer when your albums dont have cover images metadata.

**Describe the solution you'd like**
Id like to have an album view that is similar to the Artist view, presented as a list, with a small square cover art on the side.

**Describe alternatives you've considered**
If i could see the whole name of the album in the cards view that would also solve my issue. Moving text maybe, or allow multiline rendering of the album's name.

**Comment by soncaokim** [comment]
Hello,

I'm not sure to understand your request: what is the issue with the album view per line (i e. album view/top right dots menu/grid size = 1), since it offers long text view and album thumb already?

It is possible to scroll the album name (by sliding the truncated name) to see the truncated part.

**Comment by Cwpute** [comment]
Oh right, sorry… i feel bad asking now :s
This issue is completed then
