### ISSUE TITLE
Android 5.1: Files are being copied over from external storage to cache when they shouldn't be

### ISSUE THREAD

**Issue by Cynosphere** [VinylMusicPlayer/VinylMusicPlayer#812]
**Describe the bug**
Files are being copied over from external storage to cache when they shouldn't be, leading to internal storage space being eaten up, constant rescanning on app open, and slow library scanning as the device has to constantly copy files and clear cache if running out of space.

**To reproduce**
1. Have music on external storage

**Expected behavior**
Scanning is fast, storage space not being taken up.

**Device info**
 - Device: ZTE Z820
 - Android Version: 5.1
 - ROM: AOSP
 - Vinyl Music Player Version: `9a0b32d_231015-0814-ci-release`

**Comment by soncaokim** [comment]
Hello,

This is probably a side effect due to the code change to upgrade to Android
13.

The temp files are expected to auto delete. I ll try to have a look to see
what can be done

**Comment by K9100ii** [comment]
I'm able to reproduce this issue on a few of my devices with music on external storage (micro SD cards), and presumably any of them with music on an SD card. The few devices I've tried are a phone running Android 13 with LineageOS 20.0, another one running 12L with LineageOS 19.1, and finally another running 8.0 with a stock firmware from Sony.

It seems the only condition for the issue to be reproducible is to have external storage with music on it, and the Android version or device doesn't actually matter, so the title change to mention Android 5.1 doesn't appear to be right.

Interestingly, the cache size jumps around. It can go from maybe one or two hundred megabytes to 400-700+MB(!), though it seems to end up staying at 100-200MB after scanning (that's with a much cut down library than my usual one, though). Still a big waste of storage.

The performance of the app is also extremely bad while it's scanning, to the point where it's completely unusable, and after scanning (with the much cut down library) the performance still seems worse in general with the cache size jumping around as well as I play tracks. While scanning, it also freezes up entirely for my usual much larger library.

Honestly, I'm not really sure why anything should be copied over to internal storage as a temporary file. It should just be read from external storage, as it always has been and as all other apps do.

Copying unnecessarily is not a good thing (more writing to internal storage = more flash write cycles wasted), and that presumably on every play seeing as the cache size still jumps with that cut down library, especially with large audio files. The cache size was only ever under just 1MB before 1.5.3 - It should stay that way.

Especially with my full library being a few 10s of gigabytes of FLAC files, all this makes newer versions of the app unfortunately completely unusable. I'm just having to stick to the last working version - 1.5.2.

**Comment by soncaokim** [comment]
Hi, I acknowledge this is an issue. The reason is explained in https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/812#issuecomment-1763968529.

Unfortunately I dont have the time to look at it right now, I'd like to sort out other regression first (might require a more structural change to the code). 

If any one is willing to step in: This is linked to the loading of embedded art work, where I had to replace the raw File API with the Android 13 ContentProvider API. The new API is not compatible with the audio tagging library we use, hence the ugly code to copy the music to a temp file to work around the incompat.

**Comment by K9100ii** [comment]
> Hi, I acknowledge this is an issue. The reason is explained in [#812 (comment)](https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/812#issuecomment-1763968529).
> 
Yeah, alright. I did read that, but to be honest, it did seem a little vague to me and I got a little confused. Sorry in any case.
Regardless the title change to mention Android 5.1 doesn't seem right.

> Unfortunately I dont have the time to look at it right now, I'd like to sort out other regression first (might require a more structural change to the code).
> 
> If any one is willing to step in: This is linked to the loading of embedded art work, where I had to replace the raw File API with the Android 13 ContentProvider API. The new API is not compatible with the audio tagging library we use, hence the ugly code to copy the music to a temp file to work around the incompat.
That's alright. I'm not into app development, and unfortunately can't really contribute there.

Now with that more specific info, I see that app updates (and new apps) submitted to the play store must now target API level 33 for Android 13, though existing apps can still continue targetting level 31 for Android 12. I think older versions weren't critically broken, so updates on the play store maybe could've been held off for a slightly longer while, and it would've maybe been best to fully finish off the changes without workarounds and any pressure at all. Just my opinion.

It really doesn't seem right to leave such a rough workaround, especially with the large 30, 50, 80+...MB lossless audio files some may have on external storage, and I would fear that having unfinished changes might affect code quality for the worst in the long term. But anyway...

Since 1.5.2 continues working, it's fine for me in any case.

**Comment by soncaokim** [comment]
Hi,

The A13 upgrade was available on Github and F-Droid  before reaching PlayStore, but retaining a big change within this small scope wasnt enough to spot the problems. When 1.5.2 reached Play Store, there is a good round of  feedback, revealing many issues not detected before.

We will need certainly a better way to do non-reg tests, and controlled rollout.  

More importantly more contributors to this project - beta testers with diverse device/music library/os level, who are willing to reach out, go through the pain of testing and give constructive feedback like you and others have done.

Glad that you have a backup solution.

S

**Comment by soncaokim** [comment]
This should be fixed by #856

**Comment by K9100ii** [comment]
> This should be fixed by #856

I'm sorry for pestering, but am I right, from a cursory look through, to think that audio files are now directly being read, with a fallback to being cached as temporary files?

In my honest opinion, I nevertheless think that such a workaround should never be kept around. These things should always be kept "write once, read many", and not be rewritten over and over even as a fallback or a workaround. But anyway.

**Comment by soncaokim** [comment]
> > This should be fixed by #856
> 
> I'm sorry for pestering, but am I right, from a cursory look through, to think that, in summary, audio files are now directly being read, with a fallback to being cached as temporary files?
> 
> To be perfectly honest, I'm nevertheless of the thought process that such a workaround should never be kept around in any form, fallback or not. These things should always be kept "write once, read many", and not be rewritten over and over even as a fallback or a workaround. That still seems a little nasty. But anyway.

Hi,

If you have a better implementation - I'm really happy to review. 

S.

**Comment by XMA2l** [comment]
As my rescanned library is unusable since 1.6.1 (most tags seem to be picked up - though now length shows as 00:00 and files are unplayable) im staying on 1.5.6. 
I wondered a lot about missing storage space and now finally saw that there is an enourmous cache - shit ton of giant files - which also is nothing im willed to manage indefinitely. 

Though u all here have the only player i know of with legacy notification controlls - which i 100% want - im a bit irritated now on what to do ...

**Comment by Cynosphere** [comment]
I missed looking at this issue again because of influx of emails from other issues. I tested with latest CI build (79d9452_231226-0817) since I didn't want to update just yet and yes, the issue is fixed now. Storage space isn't being taken up and library scans as fast as it should.
